name: Export files

on:
  schedule:
    - cron: "0 2 * * *" # 每天执行
  workflow_dispatch:

jobs:
  convert_conf_files:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: pip3 install glob2

    - name: Convert Conf Files
      env:
        CN_DNS: ${{ secrets.CN_DNS }}
        THE_DNS: ${{ secrets.THE_DNS }}
      run: |
        python convert.py
        echo "DATE=$(date +"%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV

    - name: Create Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: converted-files
        path: converted
        
    - name: Upload Firmware To Release
      uses: ncipollo/release-action@v1
      with:
        name: R${{ env.DATE }}
        allowUpdates: true
        tag: dns
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: converted/*
